@startuml VIS-UseCases
skinparam packageStyle rectangle
left to right direction

' --- CONFIGURACIÓN VISUAL ---
skinparam usecase {
  BackgroundColor #EBF5FB
  BorderColor #2E86C1
  BorderThickness 2
  FontName Segoe UI
  FontSize 12
}
skinparam actor {
  BackgroundColor #1B4F72
  BorderColor #154360
  FontName Segoe UI
  FontSize 11
}
skinparam package {
  BackgroundColor #FDFEFE
  BorderColor #AED6F1
  FontName Segoe UI
  FontSize 13
  FontStyle bold
}
skinparam defaultFontName "Segoe UI"
skinparam defaultFontSize 12

legend top right
|= Control Documental (ISO 9001:2015) |
| **Código:** DT-UCD-VIS-001 |
| **Versión:** 1.3 |
| **Fecha:** 2026-08-03 |
| **Estado:** Completado |
| **Autor:** Juan David Julio Serrano |
endlegend

' --- ACTORES ---
actor "Inspector\nHSEQ" as HSEQ #1B4F72
actor "Técnico de\nMantenimiento" as Tecnico #1B4F72
actor "Supervisor de\nMantenimiento" as Supervisor #1B4F72
actor "Ingeniero de\nProyectos" as Ingeniero #1B4F72

' --- PAQUETE PRINCIPAL ---
package "Módulo de Convergencia Gemelo Digital (VIS)" {

  usecase "UC-VIS-008\nVisualizar Capa de\nPermisos de Trabajo" as UCVIS008 #EBF5FB
  usecase "UC-VIS-009\nNavegar Jerárquicamente\ncon Zoom Semántico" as UCVIS009 #EBF5FB
  usecase "UC-VIS-010\nVisualizar Despiece\n en 3D(Vista Explosionada)" as UCVIS010 #EBF5FB
  usecase "UC-VIS-011\nVerificar Rutas de Aislamiento (LOTO)\ny Bloqueo Activo" as UCVIS011 #EBF5FB
  usecase "UC-VIS-012\nConfigurar Jerarquía\nde Componentes 3D" as UCVIS012 #EBF5FB
  usecase "UC-VIS-033\Inspeccionar Activos sobre el\nPlano Base 2D" as UCVIS033 #EBF5FB

}

' --- RELACIONES ACTOR - CASO DE USO ---
HSEQ --> UCVIS008
Supervisor --> UCVIS033
Supervisor --> UCVIS009
Tecnico --> UCVIS010
Tecnico --> UCVIS011
Tecnico --> UCVIS033
Ingeniero --> UCVIS012

' --- RELACIONES INTER-CASOS DE USO (Include/Extend) ---
UCVIS011 ..> UCVIS009 : <<extend>>
UCVIS008 ..> UCVIS009 : <<include>>
UCVIS008 ..> UCVIS033 : <<include>>
UCVIS011 ..> UCVIS033 : <<include>>

@enduml